// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP63eaezXfEjFI_UWRz1MTLh8LP_SMggg',
    appId: '1:744794584754:android:1177f6a21b541219e2fbab',
    messagingSenderId: '744794584754',
    projectId: 'eye-care-68b1a',
    storageBucket: 'eye-care-68b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-tPy2XwPOFAzPLUNq3gLyS2glh__T2w',
    appId: '1:744794584754:ios:0fda9081d457611ee2fbab',
    messagingSenderId: '744794584754',
    projectId: 'eye-care-68b1a',
    storageBucket: 'eye-care-68b1a.appspot.com',
    androidClientId: '744794584754-05rqpdl0quj2t0sgc40fjd9c4r4g8lmv.apps.googleusercontent.com',
    iosClientId: '744794584754-ojufaamgq7e0hfv5qqg6mcj1b4g9mtrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyecareMobile',
  );

}